---
- include: repository.yml

- include: dependencies_deb.yml

- name: Install Jenkins
  sudo: yes
  apt: name=jenkins update-cache=yes state=latest
  register: jenkins_install

- include: cli.yml

- include: plugins.yml

- include: maven.yml
 
